webtalk_init -webtalk_dir C:\\Users\\coffe\\Xilinx\\The_zynq_book\\AXI_DMA_Tutorial01\\microzed_7020_dma_test_bak\\microzed_7020_dma_test_bak.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-05-19 23:14:21" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "k25n8qn2588orc5ngf7oe5t8pq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.985 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1558272316436" -context "sdk\\\\bsp/1558272316436"
webtalk_add_data -client sdk -key hwid -value "1558265569742" -context "sdk\\\\bsp/1558272316436"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1558272316436"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1558272316436"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1558272316436"
webtalk_add_data -client sdk -key uid -value "1558272317742" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key hwid -value "1558265569742" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key bspid -value "1558272316436" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key projSize -value "347.44921875" -context "sdk\\\\application/1558272317742"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key DebugCount -value "21" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1558278861668"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1558278861668"
webtalk_transmit -clientid 2057305438 -regid "" -xml C:\\Users\\coffe\\Xilinx\\The_zynq_book\\AXI_DMA_Tutorial01\\microzed_7020_dma_test_bak\\microzed_7020_dma_test_bak.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\coffe\\Xilinx\\The_zynq_book\\AXI_DMA_Tutorial01\\microzed_7020_dma_test_bak\\microzed_7020_dma_test_bak.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\coffe\\Xilinx\\The_zynq_book\\AXI_DMA_Tutorial01\\microzed_7020_dma_test_bak\\microzed_7020_dma_test_bak.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
